# config.py

ADMIN_PRIVILEGE_LEVEL = 10
DOCTOR_PRIVILEGE_LEVEL = 8
STAFF_PRIVILEGE_LEVEL = 6
PATIENT_PRIVILEGE_LEVEL = 4


ADMIN_VERIFICATION_CODE = "ADMIN"
DOCTOR_VERIFICATION_CODE = "DOCTOR"
STAFF_VERIFICATION_CODE = "STAFF"
